const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const screens={start:$('#startScreen'),game:$('#gameScreen'),result:$('#resultScreen')};
const items=[
 {name:'생수병',emoji:'🧴',type:'plastic',color:'#224c5f'},{name:'샴푸통',emoji:'🧴',type:'plastic',color:'#225f50'},{name:'종이컵',emoji:'🥤',type:'paper',color:'#5a4a28'},{name:'신문지',emoji:'📰',type:'paper',color:'#4b5363'},
 {name:'참치캔',emoji:'🥫',type:'can',color:'#5b3f45'},{name:'음료캔',emoji:'🥫',type:'can',color:'#5b4433'},{name:'잼 병',emoji:'🍯',type:'glass',color:'#3d5a40'},{name:'유리병',emoji:'🍾',type:'glass',color:'#2f5264'}
];
const typeKo={plastic:'플라스틱',paper:'종이',can:'캔',glass:'유리'};
let state, timer, current, selected=false;
function show(name){Object.values(screens).forEach(s=>s.classList.remove('screen-active'));screens[name].classList.add('screen-active')}
function start(){state={time:30,score:0,combo:0,bestCombo:0,correct:0,wrong:0,total:0,startedAt:new Date().toISOString(),events:[]};selected=false;show('game');spawn();tickHud();clearInterval(timer);timer=setInterval(tick,100)}
function tick(){state.time-=.1;if(state.time<=0){state.time=0;finish()}tickHud()}
function tickHud(){$('#timeText').textContent=state.time.toFixed(1);$('#scoreText').textContent=state.score;$('#comboText').textContent=state.combo;$('#bestText').textContent=Math.max(Number(localStorage.sortRushBest||0),state.score)}
function spawn(){current=items[Math.floor(Math.random()*items.length)];selected=false;const el=$('#item');el.className='item';el.style.setProperty('--item',current.color);el.innerHTML=`<div><span class="emoji">${current.emoji}</span><span class="name">${current.name}</span><span class="type">어느 통?</span></div>`;$('#feedback').className='feedback';$('#feedback').textContent='물건을 보고 맞는 통을 선택하세요.'}
function choose(type){if(!current||state.time<=0)return;state.total++;const ok=type===current.type;if(ok){state.combo++;state.bestCombo=Math.max(state.bestCombo,state.combo);state.correct++;const gain=100+state.combo*15;state.score+=gain;$('#feedback').className='feedback good';$('#feedback').textContent=`정답! ${typeKo[type]} +${gain}점 / 콤보 ${state.combo}`;}else{state.wrong++;state.combo=0;state.time=Math.max(0,state.time-2);$('#feedback').className='feedback bad';$('#feedback').textContent=`오답: ${current.name}은 ${typeKo[current.type]}입니다. -2초`;}
state.events.push({t:+(30-state.time).toFixed(1),item:current.name,answer:type,ok,score:state.score,combo:state.combo});tickHud();setTimeout(()=>{if(state.time>0)spawn()},260)}
function finish(){clearInterval(timer);const prev=Number(localStorage.sortRushBest||0);if(state.score>prev)localStorage.sortRushBest=String(state.score);const acc=state.total?Math.round(state.correct/state.total*100):0;show('result');$('#resultTitle').textContent= state.score>=1800?'생산 확신 후보':'검증 필요';$('#resultSummary').textContent=`30초 동안 ${state.correct}개를 맞히고 정확도 ${acc}%를 기록했습니다. 콤보가 끊긴 뒤 바로 다시 하고 싶은지가 핵심 신호입니다.`;$('#resultStats').innerHTML=`<div><span>점수</span><strong>${state.score}</strong></div><div><span>정확도</span><strong>${acc}%</strong></div><div><span>최고 콤보</span><strong>${state.bestCombo}</strong></div><div><span>오답</span><strong>${state.wrong}</strong></div>`;$('#resultJson').textContent=JSON.stringify({prototype:'sample-trash-sort-rush',score:state.score,accuracy:acc,bestCombo:state.bestCombo,correct:state.correct,wrong:state.wrong,total:state.total,startedAt:state.startedAt,endedAt:new Date().toISOString()},null,2)}
$('#startButton').addEventListener('click',start);$('#againButton').addEventListener('click',start);$('#restartButton').addEventListener('click',start);$('#item').addEventListener('click',()=>{$('#item').classList.toggle('selected');selected=$('#item').classList.contains('selected')});$('#item').addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',current?.type||''));
$$('.bin').forEach(bin=>{bin.addEventListener('click',()=>choose(bin.dataset.type));bin.addEventListener('dragover',e=>{e.preventDefault();bin.classList.add('dragover')});bin.addEventListener('dragleave',()=>bin.classList.remove('dragover'));bin.addEventListener('drop',e=>{e.preventDefault();bin.classList.remove('dragover');choose(bin.dataset.type)})});
