(() => {
 const RUN=300;
 const floors=[{name:'말하는 섬 폐허',req:0,hp:40,gold:8,scroll:.18},{name:'글루디오 던전',req:55,hp:105,gold:22,scroll:.25},{name:'용의 계곡 입구',req:150,hp:240,gold:55,scroll:.32},{name:'오만의 탑 그림자',req:340,hp:560,gold:140,scroll:.42}];
 const el=Object.fromEntries(['startScreen','gameScreen','resultScreen','timeText','powerText','goldText','clanText','knight','enemyName','enemyHp','combatText','log','floors','weaponButton','armorButton','bossButton','clanButton','weaponText','armorText','scrollText','bestText','bossText','breakText','resultTitle','resultSummary','resultStats','resultJson'].map(id=>[id,document.getElementById(id)]));
 let s,timer;
 function show(n){['startScreen','gameScreen','resultScreen'].forEach(id=>el[id].classList.remove('screen-active'));el[n+'Screen'].classList.add('screen-active')}
 function fmt(x){x=Math.max(0,Math.ceil(x));return `${String(Math.floor(x/60)).padStart(2,'0')}:${String(x%60).padStart(2,'0')}`}
 function power(){return Math.floor(18+s.weapon*28+s.armor*16+s.clan*18+s.bossKills*25)}
 function newRun(){s={elapsed:0,gold:40,scrolls:1,weapon:0,armor:0,clan:0,floor:0,best:0,enemyHp:floors[0].hp,bossKills:0,breaks:0,enchants:0,events:[]}}
 function log(msg,type='log'){el.log.textContent=msg;s.events.push({t:Math.round(s.elapsed),type,msg});if(s.events.length>90)s.events.shift()}
 function start(){clearInterval(timer);newRun();show('game');render();timer=setInterval(tick,400)}
 function tick(){s.elapsed+=.4; const f=floors[s.floor]; s.enemyHp-=power()*0.11; if(s.enemyHp<=0){s.gold+=Math.round(f.gold*(1+s.clan*.08)); if(Math.random()<f.scroll){s.scrolls++;log(`${f.name}: 강화 주문서 획득`,'scroll')} else log(`${f.name}: 아데나 획득`,'kill'); s.enemyHp=f.hp*(1+s.floor*.18); if(power()>floors[Math.min(3,s.floor+1)].req) s.best=Math.max(s.best,s.floor+1);} if(s.elapsed>=RUN)finish();render()}
 function setFloor(i){if(power()>=floors[i].req){s.floor=i;s.best=Math.max(s.best,i);s.enemyHp=floors[i].hp*(1+i*.18);log(`${floors[i].name} 입장`);render()}}
 function enchant(kind){if(s.scrolls<=0||s.gold<25)return; s.scrolls--;s.gold-=25;s.enchants++; const val=s[kind]; const safe=kind==='weapon'?3:4; const chance=Math.max(.35,.9-val*.08); if(val<safe||Math.random()<chance){s[kind]++;log(`${kind==='weapon'?'무기':'방어구'} 강화 성공 +${s[kind]}`,'enchant')} else {if(Math.random()<.45){s[kind]=0;s.breaks++;log('강화 실패: 장비 파손! +0으로 복구','break')} else {s[kind]=Math.max(0,s[kind]-1);log('강화 실패: 강화 수치 하락','fail')}} render()}
 function boss(){const need=floors[s.floor].req+80+s.floor*70; if(power()>=need){s.bossKills++;s.gold+=120*(s.floor+1);s.scrolls+=1;log('필드 보스 처치: 희귀 주문서와 아데나 획득','boss')} else {s.gold=Math.max(0,s.gold-35);log('보스 실패: 물약과 아데나 소모','boss_fail')} render()}
 function clan(){if(s.gold>=90){s.gold-=90;s.clan++;log(`혈맹 기여 완료: 혈맹 버프 Lv.${s.clan}`,'clan');render()}}
 function render(){el.timeText.textContent=fmt(RUN-s.elapsed);el.powerText.textContent=power();el.goldText.textContent=Math.floor(s.gold);el.clanText.textContent=`Lv.${s.clan}`;el.enemyName.textContent=floors[s.floor].name;el.enemyHp.style.width=`${Math.max(0,Math.min(100,s.enemyHp/(floors[s.floor].hp*(1+s.floor*.18))*100))}%`;el.combatText.textContent=`${s.floor+1}층 자동사냥 · 몬스터 HP ${Math.max(0,Math.ceil(s.enemyHp))}`;el.weaponText.textContent=`+${s.weapon}`;el.armorText.textContent=`+${s.armor}`;el.scrollText.textContent=s.scrolls;el.bestText.textContent=s.best+1;el.bossText.textContent=s.bossKills;el.breakText.textContent=s.breaks;el.floors.innerHTML=floors.map((f,i)=>`<button class="${i===s.floor?'active':''} ${power()<f.req?'locked':''}" data-floor="${i}">${i+1}. ${f.name}<br><small>요구 ${f.req} · 주문서 ${(f.scroll*100)|0}%</small></button>`).join('');el.floors.querySelectorAll('[data-floor]').forEach(b=>b.addEventListener('click',()=>setFloor(+b.dataset.floor)))}
 function finish(){clearInterval(timer);const report={id:'blood-oath-idle',highestFloor:s.best+1,combatPower:power(),weapon:s.weapon,armor:s.armor,scrolls:s.scrolls,bossKills:s.bossKills,clanLevel:s.clan,enchantAttempts:s.enchants,brokenItems:s.breaks,events:s.events,validationQuestion:'리니지라이크의 자동사냥·장비강화·보스/혈맹 기여 경쟁이 짧은 세션에서도 “강화 한 번 더/층 한 번 더” 욕구를 만드는가?'};el.resultTitle.textContent='혈맹의 탑 리포트';el.resultSummary.textContent=s.enchants>2?'강화 리스크와 층 돌파 루프까지 확인했습니다. 다음 포인트는 파손 스트레스가 재미/긴장으로 느껴지는지입니다.':'강화 시도가 부족했습니다. 주문서/아데나 공급을 더 당겨야 합니다.';el.resultStats.innerHTML=Object.entries({최고층:s.best+1,전투력:power(),무기:`+${s.weapon}`,방어구:`+${s.armor}`,보스:s.bossKills,파손:s.breaks,혈맹:`Lv.${s.clan}`}).map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('');el.resultJson.textContent=JSON.stringify(report,null,2);show('result')}
 document.getElementById('startButton').addEventListener('click',start);document.getElementById('retryButton').addEventListener('click',start);el.weaponButton.addEventListener('click',()=>enchant('weapon'));el.armorButton.addEventListener('click',()=>enchant('armor'));el.bossButton.addEventListener('click',boss);el.clanButton.addEventListener('click',clan);
})();