(() => {
 const RUN=300;
 const dungeons=[{name:'고블린 야영지',risk:1,gold:9,fame:2,req:0},{name:'망자의 광산',risk:2,gold:18,fame:5,req:55},{name:'화염 거인 레이드',risk:4,gold:44,fame:14,req:145}];
 const blessings=[{id:'training',name:'훈련 교본',desc:'강화 효율 +25%'},{id:'loot',name:'황금 계약',desc:'골드 획득 +35%'},{id:'fame',name:'길드 깃발',desc:'명성 획득 +35%'}];
 const el=Object.fromEntries(['startScreen','gameScreen','resultScreen','timeText','goldText','fameText','rebirthText','party','lanes','log','tankButton','dpsButton','healButton','raidButton','blessings','rebirthButton','bestText','raidText','wipeText','powerText','resultTitle','resultSummary','resultStats','resultJson'].map(id=>[id,document.getElementById(id)]));
 let s,timer;
 function show(n){['startScreen','gameScreen','resultScreen'].forEach(id=>el[id].classList.remove('screen-active'));el[n+'Screen'].classList.add('screen-active')}
 function fmt(x){x=Math.max(0,Math.ceil(x));return `${String(Math.floor(x/60)).padStart(2,'0')}:${String(x%60).padStart(2,'0')}`}
 function mult(id){return s.blessing===id?1.35:1}
 function trainMult(){return s.blessing==='training'?1.25:1}
 function power(){return Math.floor((s.tank*9+s.dps*14+s.heal*8)*(1+s.rebirths*.12+s.fameBank*.015))}
 function newRun(){s={elapsed:0,gold:30,fame:0,fameBank:0,rebirths:0,tank:1,dps:1,heal:1,lane:0,best:0,raids:0,wipes:0,blessing:'training',events:[]}}
 function log(msg,type='log'){el.log.textContent=msg;s.events.push({t:Math.round(s.elapsed),type,msg});if(s.events.length>80)s.events.shift()}
 function start(){clearInterval(timer);newRun();show('game');render();timer=setInterval(tick,500)}
 function tick(){s.elapsed+=.5; const dg=dungeons[s.lane]; const p=power(); const survival=s.tank*10+s.heal*12+s.fameBank*0.4; if(p>=dg.req && Math.random()<(0.34+s.dps*.015)){s.gold+=Math.round(dg.gold*mult('loot'));s.fame+=Math.round(dg.fame*mult('fame'));s.best=Math.max(s.best,s.lane);log(`${dg.name} 클리어: 골드/명성 획득`,'clear'); if(s.lane===2)s.raids++;} if(Math.random()<dg.risk*0.012 && survival<dg.risk*32){s.wipes++;s.gold=Math.max(0,s.gold-12*dg.risk);log('파티 전멸: 탱커/힐러가 부족합니다.','wipe')} if(s.elapsed>=RUN)finish();render()}
 function upgrade(role){const cost=Math.floor(25+s[role]*18); if(s.gold>=cost){s.gold-=cost;s[role]+=trainMult();log(`${roleName(role)} 강화 완료`) ;render()}}
 function roleName(r){return {tank:'탱커',dps:'딜러',heal:'힐러'}[r]}
 function setLane(i){if(power()>=dungeons[i].req*.75){s.lane=i;log(`${dungeons[i].name} 배치`);render()}}
 function raid(){setLane(2)}
 function rebirth(){const gain=Math.max(1,Math.floor((s.fame+s.best*8+s.raids*3)/18));s.fameBank+=gain;s.rebirths++;s.gold=30;s.fame=0;s.tank=1;s.dps=1;s.heal=1;s.lane=0;log(`환생: 영구 명성 +${gain}. 특성을 골라 다음 런을 가속하세요.`,'rebirth');render()}
 function selectBlessing(id){s.blessing=id;log(`${blessings.find(b=>b.id===id).name} 선택`);render()}
 function render(){el.timeText.textContent=fmt(RUN-s.elapsed);el.goldText.textContent=Math.floor(s.gold);el.fameText.textContent=s.fame;el.rebirthText.textContent=s.rebirths;el.bestText.textContent=s.best+1;el.raidText.textContent=s.raids;el.wipeText.textContent=s.wipes;el.powerText.textContent=power();el.party.innerHTML=[['tank','🛡️'],['dps','⚔️'],['heal','✨']].map(([r,ic])=>`<div class="hero"><div class="role">${ic}</div><h3>${roleName(r)} Lv.${Math.floor(s[r])}</h3><div class="bar"><i style="width:${Math.min(100,s[r]*14)}%"></i></div></div>`).join('');el.lanes.innerHTML=dungeons.map((d,i)=>`<div class="lane ${i===s.lane?'active':''}"><div><strong>${d.name}</strong><br><small>요구 ${d.req} · 위험 ${d.risk} · 보상 명성 ${d.fame}</small></div><button data-lane="${i}">배치</button></div>`).join('');el.lanes.querySelectorAll('[data-lane]').forEach(b=>b.addEventListener('click',()=>setLane(+b.dataset.lane)));el.blessings.innerHTML=blessings.map(b=>`<button class="blessing ${s.blessing===b.id?'selected':''}" data-bless="${b.id}">${b.name}<br><small>${b.desc}</small></button>`).join('');el.blessings.querySelectorAll('[data-bless]').forEach(b=>b.addEventListener('click',()=>selectBlessing(b.dataset.bless)))}
 function finish(){clearInterval(timer);const report={id:'rebirth-guild-manager',rebirths:s.rebirths,fameBank:s.fameBank,highestDungeon:s.best+1,raidClears:s.raids,wipes:s.wipes,power:power(),blessing:s.blessing,events:s.events,validationQuestion:'직접 전투보다 파티 편성/던전 배치/환생 특성 선택이 방치형 RPG의 “키우는 맛”을 더 선명하게 만드는가?'};el.resultTitle.textContent='길드 운영 종료';el.resultSummary.textContent=s.rebirths>0?'환생과 특성 선택까지 확인했습니다. 다음 판단은 특성 선택이 의미 있게 다른 성장 경로를 만드는지입니다.':'환생까지 못 갔습니다. 명성 획득/환생 요구치를 더 당겨야 합니다.';el.resultStats.innerHTML=Object.entries({환생:s.rebirths,영구명성:s.fameBank,최고던전:s.best+1,레이드:s.raids,전멸:s.wipes,전투력:power()}).map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('');el.resultJson.textContent=JSON.stringify(report,null,2);show('result')}
 document.getElementById('startButton').addEventListener('click',start);document.getElementById('retryButton').addEventListener('click',start);el.tankButton.addEventListener('click',()=>upgrade('tank'));el.dpsButton.addEventListener('click',()=>upgrade('dps'));el.healButton.addEventListener('click',()=>upgrade('heal'));el.raidButton.addEventListener('click',raid);el.rebirthButton.addEventListener('click',rebirth);
})();